name: Simple

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Puedes usar la versión de Node.js que prefieras

      - name: Install dependencies
        run: npm install  # Si estás usando Firebase o cualquier otro paquete, se instalarán aquí

      - name: Run tests
        run: npm test  # Si tienes pruebas configuradas, ejecuta npm test
